### ISSUE TITLE
Theme

### ISSUE THREAD

**Issue by AlbertoMonteiro** [johanneswuerbach/markdown-inline-mermaid#3]
Is there any way to work with themes?

I mean we are using this to build our backstage tech docs and since we have white and dark themes, the SVG that is generated doesnt conflict with white theme, but with dark, arrows and some texts use same background color `#333333`

**Comment by johanneswuerbach** [comment]
I'm not sure there is a way to achieve this with static rendering, but https://github.com/johanneswuerbach/backstage-plugin-techdocs-addon-mermaid supports also theming. Did you check this out already?

**Comment by AlbertoMonteiro** [comment]
I found a way to do a work around.

I mkdocs.yml I've add the extra css item, and the name of the css must match some regex pattern, so I named it main.xpto.min.css

Then it was loaded property from backstage, my first try I named it style.css but backstage didn't loaded.

I am not using the mermaid add-on, I use it only in CI, building the doc and saving it in a bucket.
