### ISSUE TITLE
How to set specific MermaidJs version?

### ISSUE THREAD

**Issue by andreminelli** [johanneswuerbach/markdown-inline-mermaid#5]
Hi!

It seems that - at least on my deployment - the version 8.13.7 is being used, but I have sequence diagrams that needs version 9.X or above.
Is there some way to set a specific MermaidJs, or maybe a custom JS file for it?

**Comment by johanneswuerbach** [comment]
The plugin itself is just executing the mermaid cli, so the mermaid version depends on the CLI version installed in your environment.

**Comment by andreminelli** [comment]
Got It. Thanks you!
